// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe11g3J624tKqINXHoGGmx1VkBquDOoKY',
    appId: '1:1075790335749:web:cf3cdc719404743034716c',
    messagingSenderId: '1075790335749',
    projectId: 'gofit-478c5',
    authDomain: 'gofit-478c5.firebaseapp.com',
    storageBucket: 'gofit-478c5.firebasestorage.app',
    measurementId: 'G-RYP3QGLB9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1zX_iYNDrbbNfu7jC63wKC9xXrVDrV3o',
    appId: '1:1075790335749:android:6540790279d4db8934716c',
    messagingSenderId: '1075790335749',
    projectId: 'gofit-478c5',
    storageBucket: 'gofit-478c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAGqdEqSWMIHhAvifSaErzn5iMgdW65Nw',
    appId: '1:1075790335749:ios:71718b09e935726e34716c',
    messagingSenderId: '1075790335749',
    projectId: 'gofit-478c5',
    storageBucket: 'gofit-478c5.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAGqdEqSWMIHhAvifSaErzn5iMgdW65Nw',
    appId: '1:1075790335749:ios:71718b09e935726e34716c',
    messagingSenderId: '1075790335749',
    projectId: 'gofit-478c5',
    storageBucket: 'gofit-478c5.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe11g3J624tKqINXHoGGmx1VkBquDOoKY',
    appId: '1:1075790335749:web:95f01212c74dd65734716c',
    messagingSenderId: '1075790335749',
    projectId: 'gofit-478c5',
    authDomain: 'gofit-478c5.firebaseapp.com',
    storageBucket: 'gofit-478c5.firebasestorage.app',
    measurementId: 'G-6TJ72KXR4D',
  );
}
